### ISSUE TITLE
can you tell me the version of the sumo you used?

### ISSUE THREAD

**Issue by Devoe-97** [ruyijidan/Unsmart-Traffic-Signal-using-DRL#1]

**Comment by HappyDay-design** [comment]
Sumo 1.14.1
paddlepaddle==1.8.5

![image](https://user-images.githubusercontent.com/82990411/192077884-b27a7bdf-5237-495e-ad1f-839d6bf016cf.png)

**Comment by HappyDay-design** [comment]
Errors
Inside episode counter 1
Traceback (most recent call last):
  File "/home/osboxes/Desktop/Unsmart-Traffic-Signal-using-DRL/train.py", line 245, in <module>
    main()
  File "/home/osboxes/Desktop/Unsmart-Traffic-Signal-using-DRL/train.py", line 230, in main
    total_reward, steps = run_episode(agent, env, rpm)
  File "/home/osboxes/Desktop/Unsmart-Traffic-Signal-using-DRL/train.py", line 125, in run_episode
    if temp[1] == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
